@startuml
package Outils{
    class FabriquePlateau{
        + static void getPlateauVide()
        + static void getNouveauPlateau()
    }

    class "Affichage" as affichage{
        + static void Afficher(Etat e)
    }
}
@enduml